# Generated by Django 3.1.1 on 2020-09-18 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
