# Generated by Django 3.1.1 on 2020-09-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_foodreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='title',
            field=models.CharField(default='리뷰', max_length=30),
        ),
    ]
