# Generated by Django 3.1.1 on 2020-11-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201128_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
